### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by kaspaas** [khoih-prog/ESPAsync_WiFiManager#1]
Hi, the link to https://www.ardu-badge.com/ESPAsync_WiFiManager is not working.

https://github.com/khoih-prog/ESPAsync_WiFiManager/blob/master/README.md

Error message at Ardu-badge

Whoops.

We could not find an Arduino Library called ESPAsync_WiFiManager on the Arduino Library Manager.

**Comment by khoih-prog** [comment]
@kaspaas 

Thanks for using the library.
The link was not working because the library is brand-new and has not been included into Library Manager at that time.
It's just been added and the link is OK now.
Thanks.

**Comment by kaspaas** [comment]
Thanks!
