### ISSUE TITLE
Compilation error: WiFiMulti.h: No such file or director

### ISSUE THREAD

**Issue by prakash52kar** [khoih-prog/ESPAsync_WiFiManager#128]
I have removed the Arduino folder and libraries from the PC and reinstalled the Arduino IDE 2.0.3

Then tried to compile the AsyncConfigOnSwitchFS code. However, the following got an error [Board selected was AI-ThinkerESP32CAM]

fatal error: WiFiMulti.h: No such file or directory 
compilation terminated.
exit status 1
Compilation error: WiFiMulti.h: No such file or directory

I have included the ESP32 board in preferences as well as installed WiFI by Arduino library 

The error persists 

![Screenshot (71)](https://user-images.githubusercontent.com/57166940/208487197-69d1718f-e046-492e-a81c-2c9b9f540d86.png)

### Information

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.19) or Platform.io version
* `ESP8266` or `ESP32` Core Version (e.g. ESP8266 core v3.0.2 or ESP32 v2.0.4)
* Contextual information (e.g. what you were trying to achieve)
* Simplest possible steps to reproduce
* Anything that might be relevant in your opinion, such as:
  * Operating system (Windows, Ubuntu, etc.) and the output of `uname -a`
  * Network configuration

### Example

```
Arduino IDE version: 1.8.19
ESP8266 Core Version 3.0.2
OS: Ubuntu 20.04 LTS
Linux xy-Inspiron-3593 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Context:
I encountered an endless loop while trying to connect to Local WiFi.

Steps to reproduce:
1. ...
2. ...
3. ...
4. ...
```

### Additional context

Add any other context about the problem here

---

### Sending Feature Requests

Feel free to post feature requests. It's helpful if you can explain exactly why the feature would be useful.

There are usually some outstanding feature requests in the [existing issues list](https://github.com/khoih-prog/ESPAsync_WiFiManager/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement), feel free to add comments to them.

---

### Sending Pull Requests

Pull Requests with changes and fixes are also welcome!

Please use the `astyle` to reformat the updated library code as follows (demo for Ubuntu Linux)

1. Change directory to the library GitHub

```
xy@xy-Inspiron-3593:~$ cd Arduino/xy/ESPAsync_WiFiManager_GitHub/
xy@xy-Inspiron-3593:~/Arduino/xy/ESPAsync_WiFiManager_GitHub$
```

2. Issue astyle command

```
xy@xy-Inspiron-3593:~/Arduino/xy/ESPAsync_WiFiManager_GitHub$ bash utils/restyle.sh
```

**Comment by khoih-prog** [comment]
HI @prakash52kar 

Be sure to install the IDE as well as ESP32 core correctly.

As a rule, whenever you get a fatal error, such as missing file, etc., do some basic research and check your system first, before posting the wasting-time issue

The [**WiFiMulti.h**](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiMulti.h) is in ESP32-core

![Selection_231](https://user-images.githubusercontent.com/57012152/208488654-9057cda4-8398-4efc-8254-6f9c5ddca5f1.png)

Go back to Arduino IDE v1.8.19 if you can't  figure out the issue

Good Luck
