### ISSUE TITLE
ConfigOnSwitch example flawed?

### ISSUE THREAD

**Issue by marcelstoer** [khoih-prog/ESPAsync_WiFiManager#18]
I think your ConfigOnSwitch example _might_ be flawed but I cannot be exactly sure (yet). The issue is that if the device cannot connect to one of the configured WiFi networks it keeps looping _ignoring that pressed button to start the config portal_.

I took your example and simplified it for my needs:
- remove the ESP8266/ESP32 if-defs as I only need ESP32
- remove the features I don't need
- refactored duplicated code into dedicated functions
- put all code into a `wifimanager.h` that I can use from my main `setup()`/`loop()`

-> see Gist https://gist.github.com/marcelstoer/914ff2ac58a42a957dfa071c9c5c8acd
-> use as below

```c++
void setup() {
  Serial.begin(115200);

  initWifiManager(String(deviceId));
  log_i("WiFi manager initialized.");
}

void loop() {
  // check button status here (to see if to start config portal)

  // internally checks WiFi connectivity in an interval i.e. not necessarily every time you call
  // this function
  checkWifiStatus();

  // app functions go here
}
```

As far as I understand the problem is the `while`-loop in `connectMultiWiFi()` at https://github.com/khoih-prog/ESPAsync_WiFiManager/blob/master/examples/Async_ConfigOnSwitch/Async_ConfigOnSwitch.ino#L388. 

The function sequence is like this: `loop()` -> `check_status()` -> `check_WiFi()` -> `connectMultiWiFi()`. While trying to connect to one of the WiFis in that `while`-loop pressing the button to start the config portal has no effect! You would have to press the button for a really long time until the loop ends, the sequence above returns to `loop()` and the button status is evaluated again.

**Comment by khoih-prog** [comment]
Thanks again for your interest in the library and your nice and clean code. The library's examples are normally over-crowded with too many definitions trying to demonstrate to as many use cases as possible.

The [**Async_ConfigOnSwitch** example](https://github.com/khoih-prog/ESPAsync_WiFiManager/blob/master/examples/Async_ConfigOnSwitch/Async_ConfigOnSwitch.ino) is just a simple example to demonstrate the [**ESPAsync_WiFiManager** library's](https://github.com/khoih-prog/ESPAsync_WiFiManager) feature and certainly can not be expected to be perfect in all use cases.

To make sure to enter the Config Portal whenever a button is pressed, it's suggested you use either

1. **Interrupt** for the button to change a flag, then use the **flag** to exit the WiFi while loop when the button is pressed.
2. [**Async_ConfigOnDoubleReset** example](https://github.com/khoih-prog/ESPAsync_WiFiManager/tree/master/examples/Async_ConfigOnDoubleReset)

Please check these examples

1. [**ISR_Timer_4_Switches**](https://github.com/khoih-prog/SmallProjects/blob/master/ISR_Timer_4_Switches/ISR_Timer_4_Switches.ino) 
2. [**ISR_Switch**](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/ISR_Switch/ISR_Switch.ino)
3. [**SwitchDebounce**](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/SwitchDebounce/SwitchDebounce.ino)

for how to use Button Interrupt in ESP8266/ESP32.
