### ISSUE TITLE
Compile Error on Platformio

### ISSUE THREAD

**Issue by Gwenselah** [khoih-prog/ESPAsync_WiFiManager#2]
Hello,

I try to compile the Async_ESP_FSWebServer example. On compiling I get this error:
![image](https://user-images.githubusercontent.com/47796674/92037866-bb246280-ed72-11ea-9ad3-0664e4cb03a8.png)

My platformio.ini looks like:
>[env:wemos_d1_mini32]
>platform = espressif8266
>board = d1_mini
>board_build.filesystem = littlefs
>framework = arduino
>monitor_speed = 115200
>lib_deps =
>  ESP Async WebServer
>  ESPAsyncTCP

What I am missing?

kind regards

**Comment by khoih-prog** [comment]
@Gwenselah 

Thanks for using the library.

You have to update to use the new version [**ESPAsync_WiFiManager v1.1.1**](https://github.com/khoih-prog/ESPAsync_WiFiManager/releases/tag/v1.1.1) to support MultiiFi

Check at then update either in 

1. **Platform.io** => [ESPAsync_WifiManager](https://platformio.org/lib/show/11065/ESPAsync_WifiManager)
2. **GitHub** => [ESPAsync_WiFiManager v1.1.1](https://github.com/khoih-prog/ESPAsync_WiFiManager/releases/tag/v1.1.1)

**Comment by kaspaas** [comment]
Hi,

I'm getting the same error 

![image](https://user-images.githubusercontent.com/2905086/92121126-34b36380-edfa-11ea-80e6-f387e6d24739.png)

All on rev 1.1.1

![image](https://user-images.githubusercontent.com/2905086/92121302-67f5f280-edfa-11ea-9e96-cfe3bda4e593.png)

**Comment by khoih-prog** [comment]
@Gwenselah 

If you still have the same error, try adding the forward declaration as follows:

```cpp
...
String separatorLine = "===============================================================";

uint8_t connectMultiWiFi(void);

//format bytes
String formatBytes(size_t bytes) 
...
```

**Comment by Gwenselah** [comment]
@khoih-prog This additional declaration helped to compile the code.
Thank you for your assistance

**Comment by khoih-prog** [comment]
HI @Gwenselah , @kaspaas 

Just let you know the new [**ESPAsync_WiFiManager release v1.1.2**](https://github.com/khoih-prog/ESPAsync_WiFiManager/releases/tag/v1.1.2) already fixes the issue as well as some bugs in examples.
