### ISSUE TITLE
Not working when not connected to Serial

### ISSUE THREAD

**Issue by SkyGuardian42** [khoih-prog/ESPAsync_WiFiManager#27]
The WiFi Manager doesn't work when powering the ESP32 over its VIN Port, but does when powering it through USB. I'm simply using the Code from the Async_AutoConnect_ESP32_minimal.ino example. I already remove the `while (!Serial); delay(200);` line. Is there a simple fix for this?

**Comment by SkyGuardian42** [comment]
Turns out there is a more general problem with powering the ESP32 on the VIN Pins, which has nothing to do with the library.

**Comment by khoih-prog** [comment]
I've just been back home and seen this and am happy **you did your thorough research/experiment** and found out the issue before I would inform you.

This is good experience for other new users, and will be definitely helpful. Don't hesitate to post any issue, **correct or not**, as they are all beneficial somehow to other users.

Good Luck with your project,
