### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by kaspaas** [khoih-prog/ESPAsync_WiFiManager#3]
Hi,

I'm getting the same error 

![image](https://user-images.githubusercontent.com/2905086/92121126-34b36380-edfa-11ea-80e6-f387e6d24739.png)

All on rev 1.1.1

![image](https://user-images.githubusercontent.com/2905086/92121302-67f5f280-edfa-11ea-9e96-cfe3bda4e593.png)

_Originally posted by @kaspaas in https://github.com/khoih-prog/ESPAsync_WiFiManager/issues/2#issuecomment-686492864_

**Comment by khoih-prog** [comment]
Hi @kaspaas 

Can you try adding the forward declaration as follows:

```cpp
...
String separatorLine = "===============================================================";

uint8_t connectMultiWiFi(void);

//format bytes
String formatBytes(size_t bytes) 
...
```

**Comment by kaspaas** [comment]
Works perfect!

Thanks!
