### ISSUE TITLE
Help with example DRD MQTT Medium

### ISSUE THREAD

**Issue by rtemkollos** [khoih-prog/ESPAsync_WiFiManager#30]
First of all, thanks for the work done.  I'm not a programmer, so I ask for help.

How to add a subscription and topic poll to example?

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

I'm sorry I'm currently busy and have no time to spend to help every one to use the library. I just can help if there is bug with the library or examples.

I can only suggest that you **go through the examples,** then find out yourself how to modify it to fit your use case. You can also post the issue on some forums (Arduino, ESP8266/ESP32,etc) to ask for help. For example [**Arduino Forum> Using Arduino> Programming Questions**](https://forum.arduino.cc/index.php?board=4.0).

There are many experienced people there being able to help you with your project.

Good Luck,
