### ISSUE TITLE
In which mode ist the WiFiManager?

### ISSUE THREAD

**Issue by cultur98** [khoih-prog/ESPAsync_WiFiManager#46]
One question which would help me to make my things easier.
Is there a way to find out it the WiFiManager is:
- initalizing
- in AP mode
- connected to a WiFi network
(- or maybe doing other weird things)
?

**Comment by khoih-prog** [comment]
As your requirements are **unusual** and possibly just necessary for only your use case, I won't spend any time on it.

You have spend some time yourself, to read and understand the library code, then just add some variable to let you know which step the WiFiManager is in.
