### ISSUE TITLE
Open configuration page when connected to a wifi

### ISSUE THREAD

**Issue by vietanhdev** [khoih-prog/ESPAsync_WiFiManager#52]
Hello,
After connecting to an outside wifi network, I got the IP address of my ESP-32 board.
Can I open the configuration page when my ESP has been connected to a Wifi (not in access point mode)? How can I do that?
Thank you!

**Comment by khoih-prog** [comment]
Hi,

You can't do that unless you trigger to open the Config Portal (**DRD/MRD**, switch, sotware, etc.)

Check hereafter for the reasons :

- [Accessing manager after connection #15](https://github.com/khoih-prog/ESP_WiFiManager/issues/15)
- [AP stays open #2](https://github.com/khoih-prog/Blynk_WM/issues/2)
- [Wifi Manager acts like Home Wifi Router? #12](https://github.com/khoih-prog/ESP_WiFiManager/issues/12)
