### ISSUE TITLE
Compile error esp32/rom/queue.h:39:1:

### ISSUE THREAD

**Issue by kaspaas** [khoih-prog/ESPAsync_WiFiManager#6]
![image](https://user-images.githubusercontent.com/2905086/92479786-48890c00-f1e4-11ea-8190-7d95be5ab451.png)

I don't think this is your problem - but there is a compile error 

Do you have a solution?

**Comment by khoih-prog** [comment]
I have no time to investigate this issue. It's possible installation-related.
I suggest you post the issue on the [**Platformio Forum**](https://community.platformio.org/) to ask for support as many other people has been successfully using this library with **Platform.io.**
