### ISSUE TITLE
question ModelessConnect & WiFiServer

### ISSUE THREAD

**Issue by freemanzwin** [khoih-prog/ESPAsync_WiFiManager#7]
hi. 
(sorry. poor english.)

I am testing the ModelessConnect example.

In addition, an FTP server (using WiFiServer) is used together.

ModelessConnect cannot connect to the router after rebooting after configuring the router in the portal.

Can't I use it with WifiServer(FTP server)?

Please help.

---------------------------------------
- device: ESP32
- IDE : platformIO/Arduino

- simple example
```
void setup()
{
	Serial.begin(115200);
	Serial.flush();
	delay(50);

	setupModelessConnect();  // ESPAsync_WiFiManager
	setupFTPServer();  // using WifiServer
}

void loop()
{
	loopModelessConnect();
	loopFTPServer();
}
```

**Comment by khoih-prog** [comment]
Hi @freemanzwin 

With your **minimal code**, I have no idea what and where it's not working and what you're actually doing.

I suggest you start by **running all the examples,** then pick the example **closely-fit** to your purpose, then modify according to your use case, step by step, to see where it's broken.

Selecting the **Modeless** example is possibly not the best, as it's trying to run more demanding STA+AP mode, unless you have the good reason to use.

Also remember the library is using **ESPAsyncWebServer**, so the **FTP server have to be also Async** type to avoid possible conflict. The `loopFTPServer()` in `loop()` shows that you're not using the Async version.

I don't see any issue of running the correct FTP server if you write the code correctly.

Sorry I can't help any further.
