### ISSUE TITLE
is there a way to run it "non blocking" ?

### ISSUE THREAD

**Issue by slaesh** [khoih-prog/ESPAsync_WiFiManager#88]
.. imagine that the "device" can function well without the WiFi connection!
but could "unlock" even more IF connected :)

**Comment by khoih-prog** [comment]
Please elaborate the question.

Also have a look at [**How to create a Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example), or the issue will be ignored and deleted.

I'm closing this now, and only reopen when actionable details are posted.
